Repository ruvenss/pmsrapi, pull requests merged in 2025-02, with the labels that each got.

#15 Plot Function
  manifest.json
  v1/GET/select_plot.php
  v1/general/db.php
  v1/index.php
Labels: enhancement

#21 update
  v1/locales/README.md
Labels: documentation

#28 0.0.11
  README.md
  manifest.json
  v1/DEL/delete.php
  v1/general/db.php
Labels: enhancement

#40 Improved protocol check
  v1/index.php
Labels: enhancement

#43 update deploy
  install.sh
  v1/deploy.php
Labels: bug, documentation

#44 0.0.14
  index.html
  manifest.json
  v1/index.php
Labels: enhancement

#45 database Creation
  README.md
  index.html
  manifest.json
  v1/general/db.php
Labels: enhancement
